stages:
  # - build
  # - test
  - deploy

# build:
#   stage: build
#   image: cirrusci/flutter:stable
#   before_script:
#     - flutter --version  # Verify Flutter version
#     - flutter pub get    # Fetch dependencies
#   script:
#     - flutter build apk  # Build APK
#   artifacts:
#     paths:
#       - build/app/outputs/flutter-apk/app-release.apk  # Directly reference the output file
#     expire_in: 1 week  # Keep for a week

deploy-apk:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  script:
    - aws s3 cp build/app-release.apk s3://$S3_BUCKET/ --recursive
  only:
    - main  # Deploy only on main branch